server:  port: 8080
spring:  application:    name: ${microservice.monstro.application.name}
  datasource:
    url: ${microservice.monstro.datasource.url}
    driver-class-name: ${microservice.monstro.datasource.driver-class-name}
    username: ${microservice.monstro.datasource.username}
    password: ${microservice.monstro.datasource.password}
  jpa:    database-platform: ${microservice.monstro.jpa.database-platform}    hibernate:      ddl-auto: update
  h2:
    console:      enabled: true  config:    import: optional:configserver:http://localhost:8888  eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka       logging:  config: ${microservice.log.config}          